# Generated by Django 5.1.2 on 2025-04-07 12:13

import users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_managers_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
    ]
